version: '3.8'
services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_CONN_STRING:
      POSTGRES_TEST_CONN_STRING: 
    ports:
     - "8081:8080"
    depends_on:
     - postgres

  document-service:
    build:
      context: ./document-service
      dockerfile: Dockerfile

    environment:
      AWS_REGION: 
      AWS_CRED_ID: 
      AWS_CRED_SECRET: 
      AWS_CRED_TOKEN:

      AWS_S3_BUCKET_NAME: 
      AWS_S3_DIR_UPLOAD: 

      AWS_LAMBDA_PARSER_PDF_NAME: 
      USER_SERVICE_ADRESS: http://user-service:8080/v1
      
    ports:
      - "8082:8080"

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres_db:/docker-entrypoint-initdb.d
      - ./custom-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    
    ports:
      - "5432:5432"

volumes:
  postgres-data:

